language: ruby
rvm:
  - 2.2.0
before_install:
  - gem install bundler -v 1.10.6
  - export CC="gcc-4.7"
  - export CXX="g++-4.7"
  - export LINK="gcc-4.7"
  - export LINKXX="g++-4.7"
  - gcc --version
  - g++ --version
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
